### ISSUE TITLE
win10下，无法删除已经添加的本地hosts方案

### ISSUE THREAD

**Issue by chenkai2** [eshengsky/HostsDock#2]
系统：win10
操作：选中一个已经添加的本地hosts方案点击删除按钮，弹出确认框后，点击“确定删除”按钮
预期：弹框、蒙层消失。本地hosts方案已删除。
实际：无任何动作。弹框、蒙层仍然存在。必须点取消才能继续。

**Comment by eshengsky** [comment]
@chenkai2 在最新的 v3.0.0 版本中已修复该问题。
